name: 'Action test'

on:
  workflow_dispatch: # Allow running the workflow manually

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: 'Check Minecraft updates'
        uses: ./
        id: check

      - name: Print new version info
        if: ${{ steps.check.outputs.id != '' }}
        run: "echo \"New Minecraft '${{ steps.check.outputs.type }}' released: ${{ steps.check.outputs.id }}\nUrl: ${{ steps.check.outputs.url }}\""
